# .travis.yml
language: shell

os: windows

branches:
  only:
    - master

before_install:
  - choco install python --version 3.7.0
  - python -m pip install --upgrade pip

install:
  - pip3 install -r requirements.txt

script:
  - pyinstaller.exe --onefile --icon=icon.ico Webtoon_Downloader.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/Webtoon_Downloader.exe
  skip_cleanup: true
