# .travis.yml
language: python

python:
  - 3.7

os: windows

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - pyinstaller.exe --onefile --icon=icon.ico Webtoon_Downloader.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/Webtoon_Downloader.exe
  skip_cleanup: true
